MiniBandidas - copia/Controllers/DetallePedidoController.cs
using MiniBandidas.Models.TableViewModels;
using MiniBandidas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity.Validation;
using System.Diagnostics;
using MiniBandidas.Models.ViewModels;

namespace MiniBandidas.Controllers
{
    public class DetallePedidoController : Controller
    {

        // GET: Pedido
        public ActionResult Procesar_Pedido()
        {
<<<<<<<< HEAD:MiniBandidas/Controllers/DetallePedidoController.cs
            List<DetallePedidoTableViewModel> lstPedido = null;
            using (DBMini_BandidasEntities db = new DBMini_BandidasEntities())
            {
                lstPedido = (from u in db.DetallePedido
                             join e in db.Pedido
                             on u.numPedido equals e.numPedido
                             join f in db.Producto
                             on u.idProducto equals f.id
                             join g in db.Topping
                             on u.idTopping1 equals g.id
                             join h in db.Topping
                             on u.idTopping2 equals h.id

                             orderby u.id
                             select new DetallePedidoTableViewModel
                             {
                                 id = u.id,
                                 numPedido = u.numPedido,
                                 idProducto = u.idProducto,
                                 cantidad = u.cantidad,
                                 idTopping1 = u.idTopping1,
                                 idTopping2 = u.idTopping2,
                                 Pedido = e,
                                 Producto = f,
                                 Topping1 = g,
                                 Topping2 = h,
                             }).ToList();

                return View(lstPedido);
========

            List<PedidoTableViewModel> lstPedidos = null;
            using (DBMini_BandidasEntities1 db = new DBMini_BandidasEntities1())
            {
                lstPedidos = (from p in db.Pedido
                              select new PedidoTableViewModel
                              {
                                  numPedido = p.numPedido,
                                  subtotal = p.subtotal,
                                  total = p.total                              
                                  
                              }).ToList();
                return View(lstPedidos);
            }            
        }

        [HttpPost]
        public ActionResult Crear_registro(PedidoViewModel model)
        {
            using (DBMini_BandidasEntities1 db = new DBMini_BandidasEntities1())
            {

                Pedido pedidoTO= new Pedido();

                var ultimoRegistro = db.Pedido.OrderByDescending(r => r.numPedido).FirstOrDefault();

                if (ultimoRegistro != null)
                {
                    pedidoTO.numPedido = ultimoRegistro.numPedido + 1; // Asigna el siguiente número de pedido
                }
                else
                {
                    pedidoTO.numPedido = 1; // Si no hay registros anteriores, empieza desde 1
                }

                pedidoTO.subtotal = 0;
                pedidoTO.total = 0;
                
                db.Pedido.Add(pedidoTO);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Debug.WriteLine($"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");
                        }
                    }
                }

>>>>>>>> pedidos, boton de agregar pedidos registros:MiniBandidas/Controllers/PedidoController.cs
            }
            return Redirect(Url.Content("~/Pedido/Procesar_Pedido/"));
        }
    }


        /*
        //[autorizacionUsuario(idOperacion: (1))]// Debería de poderse ver el menú aunque no haya iniciado sesión 
        public ActionResult Menu()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }*/

    }

MiniBandidas - copia/Controllers/UsuarioController.cs
using Microsoft.Win32;
using MiniBandidas.Filters;
using MiniBandidas.Models;
using MiniBandidas.Models.TableViewModels;
using MiniBandidas.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MiniBandidas.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        [autorizacionUsuario(idOperacion: (3))]
        public ActionResult Index()
        {
            List<UsuarioTableViewModel> lstUsuarios = null;
            using (DBMini_BandidasEntities1 db = new DBMini_BandidasEntities1())
            {
                lstUsuarios = (from u in db.Usuarios
                               join e in db.Estados
                               on u.estado equals e.id
                               orderby u.id
                               select new UsuarioTableViewModel
                               {
                                   id= u.id,
                                   email = u.email,
                                   cedula = u.cedula,
                                   nombre = u.nombre,
                                   apellido = u.apellido,
                                   contrasenna = u.contrasenna,
                                   telefono = u.telefono,
                                   estado = u.estado,
                                   Estados = e
                               }).ToList();
            }
            return View(lstUsuarios);
        }
        [HttpGet]
        public ActionResult Registrarse()
        {
            
            return View();
        }

        [HttpPost]

        public ActionResult Registrarse([Bind(Exclude = "estado,id")] UsuarioViewModel model)
        {
            //model.estado = 1; //asigna a la varible estado valor 1 para poder llenenar el valor estado oculto en la vista y que no reviente en

            if (!ModelState.IsValid) return View(model);
            using (var db = new DBMini_BandidasEntities1())
            {
               
                Usuarios usuarioTO = new Usuarios();
                usuarioTO.email = model.email;
                usuarioTO.cedula = (model.cedula);
                usuarioTO.nombre = model.nombre;
                usuarioTO.apellido = model.apellido;
                usuarioTO.contrasenna = model.contrasenna;
                usuarioTO.telefono = model.telefono;
                usuarioTO.estado = 1;
                db.Usuarios.Add(usuarioTO);
                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            Debug.WriteLine($"Property: {validationError.PropertyName} Error: {validationError.ErrorMessage}");
                        }
                    }
                }

            }
            return Redirect(Url.Content("~/Login/Index/"));
        }

        [HttpPost]
        [autorizacionUsuario(idOperacion: (3))]
        public ActionResult Delete(int id )
        {
            using (var db = new DBMini_BandidasEntities1())
            {
                var usuarioTO = db.Usuarios.Find(id);
                db.Entry(usuarioTO).State = System.Data.Entity.EntityState.Deleted;
                db.SaveChanges();
            }
            return Content("200");
        }

        [HttpGet]
        [autorizacionUsuario(idOperacion: (3))]
        public ActionResult Edit(int id )
        {
            UsuarioViewModel model = new UsuarioViewModel();
            using (var db = new DBMini_BandidasEntities1())
            {
                var usuarioTO = db.Usuarios.Find(id);
                var estadosTO = db.Estados;

                model.id = usuarioTO.id;
                model.email = usuarioTO.email;
                model.cedula = usuarioTO.cedula;
                model.nombre = usuarioTO.nombre;
                model.apellido = usuarioTO.apellido;
                model.contrasenna = usuarioTO.contrasenna;
                model.telefono = usuarioTO.telefono;
                model.estado = usuarioTO.estado;

            }
            return View(model);
        }

        [autorizacionUsuario(idOperacion: (3))]
        [HttpPost]
        public ActionResult Edit(UsuarioViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new DBMini_BandidasEntities1())
            {
                var usuarioTO = db.Usuarios.Find(model.id);
                usuarioTO.email = model.email;
                usuarioTO.cedula = model.cedula;
                usuarioTO.nombre = model.nombre;
                usuarioTO.apellido = model.apellido;
                usuarioTO.contrasenna = model.contrasenna;
                usuarioTO.telefono = model.telefono;
                usuarioTO.estado = model.estado;
                db.Entry(usuarioTO).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Usuario"));
        }

        
        
    }
}

MiniBandidas - copia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title MiniBandidas </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info">
        <div class="container">
            @Html.ActionLink("MiniBandidas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Nosotros", "Nosotros", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Administrador", "Index", "Administrador", new { area = "" }, new { @class = "nav-link" })</li>

                </ul>
                <div class="d-flex">
                    <a href="@Url.Action("LogOff","Logout")" class="btn btn-outline-primary" title="Cerrar Sesion">Cerrar Sesion</a>
                </div>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mini Bandidas</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiniBandidas - copia/Views/Shared/_LayoutAdministrador.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title MiniBandidas </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-info">
        <div class="container">
            @Html.ActionLink("MiniBandidas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Menu", "Menu", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Nosotros", "Nosotros", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Lista Usuarios", "Index", "Usuario", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Detalles de Pedido", "Detalle_Pedido", "DetallePedido", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pedidos", "Procesar_Pedido", "Pedido", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Carrito de Compras", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <div class="d-flex">
                        <a href="@Url.Action("LogOff","Logout")" class="btn btn-outline-primary" title="Cerrar Sesion">Cerrar Sesion</a>
                    </div>
                    </ul>
            </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mini Bandidas</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MiniBandidas - copia/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="bg-dark ">
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>